schema_version = 2
model = "post_four_tes"

[circuit]
I_bias = "715[uA]"

[tes."east.b".circuit]
I_bias = "700[uA]"

[pulse]
energy = "1332[keV]"
start = "20.02[ms]"
duration = "1[ns]"
sigma = "50[um]"
center = "auto"
