"""Build the single-pixel hybrid mesh geometry.

The absorber remains an unstructured tetrahedral volume.  The supporting
stack is generated by extruding triangular 2-D footprints through each layer,
which produces 6-node prisms.  It intentionally writes a separate MSH file
(`gmsh/project_hybrid_prism.msh`) so it cannot overwrite the established
all-tetrahedral comparison mesh.
"""
from __future__ import annotations

import argparse
import math
import json
import sys
from collections import Counter, defaultdict
from pathlib import Path

import gmsh

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

from scripts.support.reconcile_project import reconcile_project


DEFAULT_OUT = ROOT / "gmsh" / "project_hybrid_prism.msh"
DEFAULT_PROJECT = ROOT / "elmer_project_comsol_timegrid.json"
GLOBAL_STACK_SIZE = 50.0e-6
MAX_INTERFACE_FACE_COUNT_RATIO = 4.0
MIN_PRISM_SICN = 0.01
MEMBRANE_PRISM_BODIES = ("Membrane_SiNx", "Membrane_Si1")
# OCC bounding boxes can differ from the analytic plane by roughly 1e-7 m.
TOL = 1.0e-8


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    """Parse the geometry recipe without initializing Gmsh.

    The optional stack probe is deliberately opt-in: absent arguments retain
    the established uniform 50 um hybrid geometry recipe.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("project", nargs="?", type=Path, default=DEFAULT_PROJECT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUT)
    parser.add_argument(
        "--global-mesh-size", type=float, default=GLOBAL_STACK_SIZE, metavar="METERS",
        help="uniform background size outside the local refinement fields (default: legacy 50 um)",
    )
    parser.add_argument(
        "--stack-local-size", type=float, default=None, metavar="METERS",
        help="central stack/contact Box-field size; omit for a uniform mesh at --global-mesh-size",
    )
    parser.add_argument(
        "--stack-local-half-width", type=float, default=0.4e-3, metavar="METERS",
        help="half-width of the central stack/contact refinement box (default: 0.4 mm)",
    )
    parser.add_argument(
        "--absorber-local-size", type=float, default=None, metavar="METERS",
        help="absorber-centre Ball-field size; omit for no absorber-local refinement",
    )
    parser.add_argument(
        "--absorber-local-radius", type=float, default=150e-6, metavar="METERS",
        help="radius of the absorber-centre refinement ball (default: 150 um)",
    )
    parser.add_argument(
        "--disable-mesh-size-extend-from-boundary", action="store_true",
        help="disable Gmsh Mesh.MeshSizeExtendFromBoundary for a local-field probe",
    )
    parser.add_argument(
        "--mesh-algorithm", type=int, choices=range(1, 10), default=6, metavar="ID",
        help="Gmsh 2-D mesh algorithm ID (default: 6, Frontal-Delaunay)",
    )
    parser.add_argument(
        "--stycast-diameter", type=float, default=498.0e-6, metavar="METERS",
        help="Stycast disk diameter; default retains the established 498 um geometry",
    )
    parser.add_argument(
        "--stycast-layers", type=int, default=1, metavar="COUNT",
        help="number of prism elements through the Stycast thickness (default: 1)",
    )
    parser.add_argument(
        "--conformal-tes-stack", action="store_true",
        help=(
            "imprint the TES rectangle and Stycast disk into the stack footprint so "
            "TES/Membrane and Stycast/TES share nodes (no mortar); only Stycast/abs "
            "remains nonconforming"
        ),
    )
    parser.add_argument(
        "--conformal-abs", action="store_true",
        help="with --conformal-tes-stack, also make Stycast/abs node-conforming (no mortar at all)",
    )
    parser.add_argument(
        "--tes-x-positions", type=str, default=None, metavar="X1,X2,...",
        help=(
            "multi-TES (PoST) layout: x offsets in metres of the TES stacks from the "
            "pixel centre; each stack is a full chip (Si_dx x Si_dy) and bodies get a "
            "_T<k> suffix.  Omit for the single-pixel geometry (unchanged)."
        ),
    )
    parser.add_argument(
        "--absorber-length", type=float, default=None, metavar="METERS",
        help="multi-TES absorber length along x (default: TES span + abs_dx)",
    )
    parser.add_argument(
        "--absorber-refine-x", type=str, default=None, metavar="X1,X2,...",
        help=(
            "extra absorber refinement balls (same size/radius as --absorber-local-*) at "
            "these x offsets, e.g. the pulse positions of a PoST scan"
        ),
    )
    for name, help_name in (
        ("sio2-2", "lower SiO2"),
        ("si-2", "lower Si"),
        ("sio2-1", "upper SiO2"),
        ("si-1", "upper Si"),
        ("sinx", "SiNx"),
        ("tes", "TES"),
    ):
        parser.add_argument(
            f"--{name}-layers", type=int, default=1, metavar="COUNT",
            help=f"number of prism elements through the {help_name} thickness (default: 1)",
        )
    args = parser.parse_args(argv)
    if args.global_mesh_size <= 0.0:
        parser.error("--global-mesh-size must be positive")
    if args.stack_local_size is not None and args.stack_local_size <= 0.0:
        parser.error("--stack-local-size must be positive")
    if args.stack_local_size is not None and args.stack_local_size > args.global_mesh_size:
        parser.error("--stack-local-size may not exceed --global-mesh-size")
    if args.stack_local_half_width <= 0.0:
        parser.error("--stack-local-half-width must be positive")
    if args.absorber_local_size is not None and args.absorber_local_size <= 0.0:
        parser.error("--absorber-local-size must be positive")
    if args.absorber_local_size is not None and args.absorber_local_size > args.global_mesh_size:
        parser.error("--absorber-local-size may not exceed --global-mesh-size")
    if args.absorber_local_radius <= 0.0:
        parser.error("--absorber-local-radius must be positive")
    if args.stycast_diameter <= 0.0:
        parser.error("--stycast-diameter must be positive")
    if args.conformal_abs and not args.conformal_tes_stack:
        parser.error("--conformal-abs requires --conformal-tes-stack")
    args.tes_x = _parse_positions(parser, args.tes_x_positions, "--tes-x-positions")
    args.refine_x = _parse_positions(parser, args.absorber_refine_x, "--absorber-refine-x") or []
    if args.tes_x is not None and not args.conformal_tes_stack:
        parser.error("--tes-x-positions requires --conformal-tes-stack")
    if args.absorber_length is not None and args.absorber_length <= 0.0:
        parser.error("--absorber-length must be positive")
    for name in ("stycast", "sio2_2", "si_2", "sio2_1", "si_1", "sinx", "tes"):
        if getattr(args, f"{name}_layers") < 1:
            parser.error(f"--{name.replace('_', '-')}-layers must be at least 1")
    return args


def _parse_positions(parser, text: str | None, flag: str) -> list[float] | None:
    if text is None:
        return None
    try:
        values = [float(v) for v in text.split(",") if v.strip()]
    except ValueError:
        parser.error(f"{flag} must be a comma-separated list of numbers")
    if not values:
        parser.error(f"{flag} is empty")
    return values


def stack_local_field_profile(
    local_size: float | None,
    half_width: float,
    x0: float,
    y0: float,
    z_sio2_1: float,
    z_abs: float,
    global_size: float = GLOBAL_STACK_SIZE,
) -> dict[str, float] | None:
    """Return a pure Gmsh Box-field profile for the optional stack probe."""
    if local_size is None or local_size >= global_size:
        return None
    return {
        "VIn": local_size,
        "VOut": global_size,
        "XMin": x0 - half_width,
        "XMax": x0 + half_width,
        "YMin": y0 - half_width,
        "YMax": y0 + half_width,
        # Extend one nominal global cell below SiO2_1 so the transition is
        # smooth through the membrane/stack column. The top is the absorber
        # contact plane; this necessarily refines tetrahedra adjacent to the
        # absorber-bottom interface but not the absorber bulk.
        "ZMin": z_sio2_1 - global_size,
        "ZMax": z_abs,
        "Thickness": global_size,
    }


def absorber_local_field_profile(
    local_size: float | None,
    radius: float,
    x0: float,
    y0: float,
    z_abs: float,
    abs_z: float,
    global_size: float = GLOBAL_STACK_SIZE,
) -> dict[str, float] | None:
    """Return a pure Gmsh Ball-field profile for absorber-centre refinement."""
    if local_size is None or local_size >= global_size:
        return None
    return {
        "VIn": local_size,
        "VOut": global_size,
        "XCenter": x0,
        "YCenter": y0,
        "ZCenter": z_abs + abs_z / 2.0,
        "Radius": radius,
        "Thickness": global_size,
    }


def configure_local_fields(
    stack_profile: dict[str, float] | list | None,
    absorber_profile: dict[str, float] | list | None,
) -> None:
    """Install optional Box/Ball fields, combining active fields with Min.

    Each argument is one profile or a list of them (one per TES stack /
    absorber refinement point); Box fields come first, as before."""
    def as_list(profile):
        if profile is None:
            return []
        return list(profile) if isinstance(profile, list) else [profile]
    active_profiles = [("Box", q) for q in as_list(stack_profile)] + \
        [("Ball", q) for q in as_list(absorber_profile)]
    field_ids: list[int] = []
    for field_type, profile in active_profiles:
        if profile is None:
            continue
        field = gmsh.model.mesh.field.add(field_type)
        for name, value in profile.items():
            gmsh.model.mesh.field.setNumber(field, name, value)
        field_ids.append(field)
    if not field_ids:
        return
    if len(field_ids) == 1:
        gmsh.model.mesh.field.setAsBackgroundMesh(field_ids[0])
        return
    minimum = gmsh.model.mesh.field.add("Min")
    gmsh.model.mesh.field.setNumbers(minimum, "FieldsList", field_ids)
    gmsh.model.mesh.field.setAsBackgroundMesh(minimum)


def configure_stack_local_field(profile: dict[str, float] | None) -> None:
    """Compatibility adapter for callers that only install the stack Box field."""
    configure_local_fields(profile, None)


def configure_mesh_size_options(disable_extend_from_boundary: bool) -> None:
    """Apply the opt-in size-extension override without changing other sources."""
    if disable_extend_from_boundary:
        gmsh.option.setNumber("Mesh.MeshSizeExtendFromBoundary", 0)


def assess_mesh_quality(
    tes_face_elements: int,
    membrane_face_elements: int,
    membrane_prism_qualities: dict[str, list[float]],
) -> list[str]:
    """Return rejection reasons for the TES/membrane mesh quality contract.

    This deliberately contains no Gmsh calls so the acceptance thresholds are
    testable without generating a full 3-D mesh.
    """
    reasons: list[str] = []
    if tes_face_elements < 1 or membrane_face_elements < 1:
        reasons.append(
            "TES__zmin and Membrane_SiNx__zmax must both contain 2-D elements "
            f"(TES={tes_face_elements}, Membrane_SiNx={membrane_face_elements})"
        )
    else:
        ratio = max(tes_face_elements, membrane_face_elements) / min(tes_face_elements, membrane_face_elements)
        if ratio > MAX_INTERFACE_FACE_COUNT_RATIO:
            reasons.append(
                "TES__zmin/Membrane_SiNx__zmax 2-D element-count ratio "
                f"{ratio:.3g} exceeds {MAX_INTERFACE_FACE_COUNT_RATIO:g} "
                f"(TES={tes_face_elements}, Membrane_SiNx={membrane_face_elements})"
            )
    for body in MEMBRANE_PRISM_BODIES:
        qualities = membrane_prism_qualities.get(body, [])
        if not qualities:
            reasons.append(f"{body} contains no 6-node prism elements to evaluate")
            continue
        minimum = min(qualities)
        if minimum < MIN_PRISM_SICN:
            reasons.append(
                f"{body} prism minSICN {minimum:.6g} is below {MIN_PRISM_SICN:g} "
                f"({sum(value < MIN_PRISM_SICN for value in qualities)} prism elements below limit)"
            )
    return reasons


def _physical_surface_element_count(name: str) -> int:
    """Count all 2-D elements belonging to one named physical surface."""
    groups = [tag for dim, tag in gmsh.model.getPhysicalGroups(2) if gmsh.model.getPhysicalName(dim, tag) == name]
    if len(groups) != 1:
        raise RuntimeError(f"expected exactly one physical surface named {name!r}, got {len(groups)}")
    return sum(
        len(element_tags)
        for entity in gmsh.model.getEntitiesForPhysicalGroup(2, groups[0])
        for element_tags in gmsh.model.mesh.getElements(2, entity)[1]
    )


def _physical_volume_prism_qualities(name: str) -> list[float]:
    """Return minSICN values for 6-node prisms in one named physical volume."""
    groups = [tag for dim, tag in gmsh.model.getPhysicalGroups(3) if gmsh.model.getPhysicalName(dim, tag) == name]
    if len(groups) != 1:
        raise RuntimeError(f"expected exactly one physical volume named {name!r}, got {len(groups)}")
    prism_tags = [
        tag
        for entity in gmsh.model.getEntitiesForPhysicalGroup(3, groups[0])
        for element_type, tags in zip(*gmsh.model.mesh.getElements(3, entity)[:2])
        if element_type == 6
        for tag in tags
    ]
    return [float(value) for value in gmsh.model.mesh.getElementQualities(prism_tags, "minSICN")]


def measure_mesh_quality(suffixes: list[str] | None = None) -> dict:
    """Measure interface quality, retaining global and membrane-body diagnostics.

    *suffixes* are the TES stack body suffixes ("" for a single pixel,
    "_T1".."_TN" for a multi-TES layout); every stack must pass."""
    suffixes = suffixes or [""]
    if suffixes != [""]:
        merged: dict = {"reasons": [], "membrane_prism_stats": {}}
        for sfx in suffixes:
            q = _measure_stack_quality(sfx)
            merged["reasons"] += [f"[{sfx.lstrip('_')}] {r}" for r in q["reasons"]]
            merged["membrane_prism_stats"].update({f"{b}{sfx}": v for b, v in q["membrane_prism_stats"].items()})
            for key in ("tes_face_elements", "membrane_face_elements"):
                merged[key] = merged.get(key, 0) + q[key]
            for key in ("prism_count", "prism_min_sicn", "prism_below_min_sicn"):
                merged[key] = q[key]
        return merged
    return _measure_stack_quality("")


def _measure_stack_quality(sfx: str) -> dict:
    tes_face_elements = _physical_surface_element_count(f"TES{sfx}__zmin")
    membrane_face_elements = _physical_surface_element_count(f"Membrane_SiNx{sfx}__zmax")
    types, element_tags_by_type, _ = gmsh.model.mesh.getElements(3)
    prism_tags = [tag for element_type, tags in zip(types, element_tags_by_type) if element_type == 6 for tag in tags]
    prism_qualities = [float(value) for value in gmsh.model.mesh.getElementQualities(prism_tags, "minSICN")]
    membrane_qualities = {body: _physical_volume_prism_qualities(f"{body}{sfx}") for body in MEMBRANE_PRISM_BODIES}
    membrane_stats = {
        body: {
            "prism_count": len(qualities),
            "prism_min_sicn": min(qualities) if qualities else float("nan"),
            "prism_below_min_sicn": sum(value < MIN_PRISM_SICN for value in qualities),
        }
        for body, qualities in membrane_qualities.items()
    }
    return {
        "tes_face_elements": tes_face_elements,
        "membrane_face_elements": membrane_face_elements,
        "prism_count": len(prism_qualities),
        "prism_min_sicn": min(prism_qualities) if prism_qualities else float("nan"),
        "prism_below_min_sicn": sum(value < MIN_PRISM_SICN for value in prism_qualities),
        "membrane_prism_stats": membrane_stats,
        "reasons": assess_mesh_quality(tes_face_elements, membrane_face_elements, membrane_qualities),
    }


def inspect_mesh_file(path: Path) -> dict[str, float | int | list[str]]:
    """Open an existing MSH and apply the same quality contract as generation.

    Gmsh is always finalized, including when opening or measuring fails, so a
    resume-time inspection cannot poison a later Gmsh invocation.
    """
    gmsh.initialize()
    try:
        gmsh.open(str(path))
        return measure_mesh_quality()
    finally:
        gmsh.finalize()


def _surface_at_z(tags: list[int], z: float) -> list[int]:
    result: list[int] = []
    for tag in tags:
        bb = gmsh.model.getBoundingBox(2, tag)
        if abs(bb[2] - z) < TOL and abs(bb[5] - z) < TOL:
            result.append(tag)
    return result


def _extrude(faces: list[int], dz: float, layers: int = 1) -> tuple[list[int], list[int]]:
    """Extrude triangular faces into prisms and return (volumes, top faces)."""
    result = gmsh.model.occ.extrude(
        [(2, face) for face in faces], 0.0, 0.0, dz,
        numElements=[layers], heights=[1.0], recombine=True,
    )
    volumes = [tag for dim, tag in result if dim == 3]
    gmsh.model.occ.synchronize()
    # OCC returns, for every input face, its translated top face first,
    # followed by the new volume and lateral faces.
    tops = [tag for dim, tag in result[: len(faces)] if dim == 2]
    return volumes, sorted(set(tops))


def _extrude_partitioned(faces: list[int], dz: float, layers: int = 1) -> list[tuple[int, int]]:
    """Extrude adjacent faces together and return (volume, top-face) pairs."""
    result = gmsh.model.occ.extrude(
        [(2, face) for face in faces], 0.0, 0.0, dz,
        numElements=[layers], heights=[1.0], recombine=True,
    )
    pairs = [
        (result[i + 1][1], tag)
        for i, (dim, tag) in enumerate(result[:-1])
        if dim == 2 and result[i + 1][0] == 3
    ]
    if len(pairs) != len(faces):
        raise RuntimeError(f"expected {len(faces)} extruded prism volumes, got {len(pairs)}")
    gmsh.model.occ.synchronize()
    return pairs


def _join_ring_and_centre(ring_faces: list[int], centre: int) -> tuple[list[int], list[int]]:
    """Make the membrane square share the ring's topological boundary."""
    result, _ = gmsh.model.occ.fragment(
        [(2, face) for face in ring_faces], [(2, centre)],
        removeObject=True, removeTool=True,
    )
    gmsh.model.occ.synchronize()
    faces = [tag for dim, tag in result if dim == 2]
    inner = [tag for tag in faces if gmsh.model.occ.getMass(2, tag) <= 1.01 * 0.7e-3 * 0.7e-3]
    outer = [tag for tag in faces if tag not in inner]
    if len(inner) != 1 or not outer:
        raise RuntimeError(f"failed to partition membrane footprint: inner={inner}, outer={outer}")
    return outer, inner


def _imprint_tes_footprint(
    centre_faces: list[int], x0: float, y0: float, tes_x: float, tes_y: float, sty_d: float, z: float,
) -> tuple[list[int], list[str]]:
    """Split the membrane footprint into annulus / TES-outside-disk / disk.

    The pieces are extruded through every stack layer, so the TES outline and
    the Stycast disk appear as shared mesh edges on the membrane top and the
    TES top.  Returns the faces and a parallel list of their kinds.
    """
    tes = _rectangle(x0 - tes_x / 2.0, x0 + tes_x / 2.0, y0 - tes_y / 2.0, y0 + tes_y / 2.0, z)
    disk = gmsh.model.occ.addDisk(x0, y0, z, sty_d / 2.0, sty_d / 2.0)
    result, _ = gmsh.model.occ.fragment(
        [(2, face) for face in centre_faces], [(2, tes), (2, disk)],
        removeObject=True, removeTool=True,
    )
    gmsh.model.occ.synchronize()
    faces = [tag for dim, tag in result if dim == 2]
    kinds: list[str] = []
    r_disk = sty_d / 2.0
    # OCC bounding boxes carry a ~1e-7 m tolerance, so classify by exact
    # area: the three pieces are the disk, the TES rectangle minus the disk
    # and the membrane square minus the TES rectangle.
    disk_area = math.pi * r_disk * r_disk
    tes_outer_area = tes_x * tes_y - disk_area
    for face in faces:
        area = gmsh.model.occ.getMass(2, face)
        if abs(area - disk_area) < 1.0e-4 * disk_area:
            kinds.append("disk")
        elif abs(area - tes_outer_area) < 1.0e-4 * tes_x * tes_y:
            kinds.append("tes_outer")
        else:
            kinds.append("annulus")
    counts = Counter(kinds)
    if counts["disk"] != 1 or counts["tes_outer"] < 1 or counts["annulus"] < 1:
        raise RuntimeError(f"failed to imprint TES/Stycast footprint: {dict(counts)}")
    tes_area = sum(gmsh.model.occ.getMass(2, f) for f, k in zip(faces, kinds) if k != "annulus")
    if abs(tes_area - tes_x * tes_y) > 1.0e-6 * tes_x * tes_y:
        raise RuntimeError(f"imprinted TES area {tes_area} != {tes_x * tes_y}")
    return faces, kinds


def _rectangle(xmin: float, xmax: float, ymin: float, ymax: float, z: float) -> int:
    return gmsh.model.occ.addRectangle(xmin, ymin, z, xmax - xmin, ymax - ymin)


def _ring(xmin: float, xmax: float, ymin: float, ymax: float, ixmin: float, ixmax: float, iymin: float, iymax: float, z: float) -> list[int]:
    outer = _rectangle(xmin, xmax, ymin, ymax, z)
    inner = _rectangle(ixmin, ixmax, iymin, iymax, z)
    faces, _ = gmsh.model.occ.cut([(2, outer)], [(2, inner)], removeObject=True, removeTool=True)
    gmsh.model.occ.synchronize()
    return [tag for dim, tag in faces if dim == 2]


def _add_physical_volumes(volumes: dict[str, list[int]]) -> None:
    for name, tags in volumes.items():
        gmsh.model.addPhysicalGroup(3, tags)
        gmsh.model.setPhysicalName(3, gmsh.model.getPhysicalGroups(3)[-1][1], name)


def _add_boundary_groups(faces_by_name: dict[str, dict[str, list[int]]], bath_faces: list[int]) -> None:
    # Keep the exact base/top faces returned by OCC extrusion.  Querying their
    # bounding boxes is unreliable here: OCC expands an analytic plane's box
    # by a tolerance larger than the 0.16 um TES thickness.
    for name, faces_by_side in faces_by_name.items():
        for suffix in ("zmin", "zmax"):
            # The bath is this exact physical face.  Gmsh/ElmerGrid retain
            # one physical label per boundary entity, so do not also name it
            # SiO2_2__zmin.
            if (name == "SiO2_2" or name.startswith("SiO2_2_T")) and suffix == "zmin":
                continue
            faces = sorted(set(faces_by_side.get(suffix, [])))
            if faces:
                group = gmsh.model.addPhysicalGroup(2, faces)
                gmsh.model.setPhysicalName(2, group, f"{name}__{suffix}")
    group = gmsh.model.addPhysicalGroup(2, bath_faces)
    gmsh.model.setPhysicalName(2, group, "bath")


def _build_stack(args, p, xc, y0, sfx, volumes, faces_by_name, z, dims):
    """One TES chip stack (SiO2_2 .. Stycast) centred at (xc, y0), body
    names suffixed with *sfx*.  Returns (bath faces, Stycast top faces)."""
    outer_x, outer_y, mem_x, mem_y, tes_x, tes_y, tes_z, sty_d, sty_z = dims
    z_sio2_2, z_sio2_1, z_tes, z_sty = z["z_sio2_2"], z["z_sio2_1"], z["z_tes"], z["z_sty"]
    ox0, ox1 = xc - outer_x / 2.0, xc + outer_x / 2.0
    oy0, oy1 = y0 - outer_y / 2.0, y0 + outer_y / 2.0
    mx0, mx1 = xc - mem_x / 2.0, xc + mem_x / 2.0
    my0, my1 = y0 - mem_y / 2.0, y0 + mem_y / 2.0
    sty_top: list[int] = []
    ring = _ring(ox0, ox1, oy0, oy1, mx0, mx1, my0, my1, z_sio2_2)
    v, ring_top = _extrude(ring, p["SiO2_2_dz"], args.sio2_2_layers)
    volumes["SiO2_2" + sfx] += v
    faces_by_name["SiO2_2" + sfx]["zmin"] += ring
    faces_by_name["SiO2_2" + sfx]["zmax"] += ring_top
    v, ring_top = _extrude(ring_top, p["Si_2_dz"], args.si_2_layers)
    volumes["Si_2" + sfx] += v
    faces_by_name["Si_2" + sfx]["zmin"] += faces_by_name["SiO2_2" + sfx]["zmax"]
    faces_by_name["Si_2" + sfx]["zmax"] += ring_top

    # At the Si_2 top the membrane cavity is closed by SiO2_1. Fragment the
    # existing Si_2 top face with the centre square, then extrude both faces
    # in one operation. This keeps all layer interfaces conforming.
    centre = _rectangle(mx0, mx1, my0, my1, z_sio2_1)
    ring_top, centre_faces = _join_ring_and_centre(ring_top, centre)
    faces_by_name["Si_2" + sfx]["zmax"] = list(ring_top)
    # Per centre face: "annulus", "tes_outer" or "disk".  Extrusion keeps the
    # input order, so this list stays parallel to centre_top below.
    centre_kind = ["annulus"] * len(centre_faces)
    if args.conformal_tes_stack:
        centre_faces, centre_kind = _imprint_tes_footprint(
            centre_faces, xc, y0, tes_x, tes_y, sty_d, z_sio2_1
        )

    pairs = _extrude_partitioned(ring_top + centre_faces, p["SiO2_1_dz"], args.sio2_1_layers)
    split = len(ring_top)
    volumes["SiO2_1" + sfx] += [vol for vol, _ in pairs]
    faces_by_name["SiO2_1" + sfx]["zmin"] += ring_top + centre_faces
    ring_top = [top for _, top in pairs[:split]]
    centre_top = [top for _, top in pairs[split:]]
    faces_by_name["SiO2_1" + sfx]["zmax"] += ring_top + centre_top

    pairs = _extrude_partitioned(ring_top + centre_top, p["Si_1_dz"], args.si_1_layers)
    split = len(ring_top)
    volumes["Si_1" + sfx] += [vol for vol, _ in pairs[:split]]
    volumes["Membrane_Si1" + sfx] += [vol for vol, _ in pairs[split:]]
    faces_by_name["Si_1" + sfx]["zmin"] += ring_top
    faces_by_name["Membrane_Si1" + sfx]["zmin"] += centre_top
    ring_top = [top for _, top in pairs[:split]]
    centre_top = [top for _, top in pairs[split:]]
    faces_by_name["Si_1" + sfx]["zmax"] += ring_top
    faces_by_name["Membrane_Si1" + sfx]["zmax"] += centre_top

    pairs = _extrude_partitioned(ring_top + centre_top, p["SiNx_dz"], args.sinx_layers)
    split = len(ring_top)
    volumes["SiNx" + sfx] += [vol for vol, _ in pairs[:split]]
    volumes["Membrane_SiNx" + sfx] += [vol for vol, _ in pairs[split:]]
    faces_by_name["SiNx" + sfx]["zmin"] += ring_top
    faces_by_name["Membrane_SiNx" + sfx]["zmin"] += centre_top
    ring_top = [top for _, top in pairs[:split]]
    centre_top = [top for _, top in pairs[split:]]
    faces_by_name["SiNx" + sfx]["zmax"] += ring_top
    if not args.conformal_tes_stack:
        faces_by_name["Membrane_SiNx" + sfx]["zmax"] += centre_top

        tes = _rectangle(xc - tes_x / 2.0, xc + tes_x / 2.0, y0 - tes_y / 2.0, y0 + tes_y / 2.0, z_tes)
        v, _ = _extrude([tes], tes_z, args.tes_layers)
        volumes["TES" + sfx] += v
        faces_by_name["TES" + sfx]["zmin"] += [tes]
        faces_by_name["TES" + sfx]["zmax"] += _
        disk = gmsh.model.occ.addDisk(xc, y0, z_sty, sty_d / 2.0, sty_d / 2.0)
        v, _ = _extrude([disk], sty_z, layers=args.stycast_layers)
        volumes["Stycast" + sfx] += v
        faces_by_name["Stycast" + sfx]["zmin"] += [disk]
        faces_by_name["Stycast" + sfx]["zmax"] += _
    else:
        # TES grows from its imprinted footprint on the membrane top and the
        # Stycast from the imprinted disk on the TES top: both interfaces are
        # the same OCC faces on either side, hence node-conforming.
        faces_by_name["Membrane_SiNx" + sfx]["zmax"] += [f for f, k in zip(centre_top, centre_kind) if k == "annulus"]
        tes_base = [f for f, k in zip(centre_top, centre_kind) if k != "annulus"]
        tes_kind = [k for k in centre_kind if k != "annulus"]
        pairs = _extrude_partitioned(tes_base, tes_z, args.tes_layers)
        volumes["TES" + sfx] += [vol for vol, _ in pairs]
        faces_by_name["TES" + sfx]["zmin"] += tes_base
        tes_top = [top for _, top in pairs]
        disk_top = [f for f, k in zip(tes_top, tes_kind) if k == "disk"]
        faces_by_name["TES" + sfx]["zmax"] += [f for f, k in zip(tes_top, tes_kind) if k != "disk"]
        v, sty_top = _extrude(disk_top, sty_z, layers=args.stycast_layers)
        volumes["Stycast" + sfx] += v
        faces_by_name["Stycast" + sfx]["zmin"] += disk_top
        faces_by_name["Stycast" + sfx]["zmax"] += sty_top

    return list(faces_by_name["SiO2_2" + sfx]["zmin"]), list(sty_top)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    raw = json.loads(args.project.read_text(encoding="utf-8"))
    model = reconcile_project(raw)
    p = model["parameters"]

    # Coordinates are derived from the same resolved single-pixel geometry as
    # mesh_refined_3x.  The lateral origin is x=0, y=1 mm.
    x0, y0 = 0.0, 1.0e-3
    outer_x, outer_y = p["Si_dx"], p["Si_dy"]
    mem_x, mem_y = p["membrane_dx"], p["membrane_dy"]
    abs_x, abs_y, abs_z = p["abs_dx"], p["abs_dy"], p["abs_dz"]
    tes_x, tes_y, tes_z = p["TES_Au_dx"], p["TES_Au_dy"], p["TES_dz"]
    sty_d, sty_z = args.stycast_diameter, p["Stycast_dz"]
    z0 = -0.5 * p["Si_2_dz"] - p["SiO2_2_dz"]
    z_sio2_2 = z0
    z_si2 = z_sio2_2 + p["SiO2_2_dz"]
    z_sio2_1 = z_si2 + p["Si_2_dz"]
    z_si1 = z_sio2_1 + p["SiO2_1_dz"]
    z_sinx = z_si1 + p["Si_1_dz"]
    z_tes = z_sinx + p["SiNx_dz"]
    z_sty = z_tes + tes_z
    z_abs = z_sty + sty_z

    # Single pixel: one stack at the pixel centre, unsuffixed body names.
    # Multi-TES (PoST): one full chip stack per TES x offset, bodies "_T<k>",
    # all under one long absorber.
    multi = args.tes_x is not None
    stack_x = [x0 + dx for dx in args.tes_x] if multi else [x0]
    suffixes = [f"_T{k}" for k in range(1, len(stack_x) + 1)] if multi else [""]
    if multi:
        order = sorted(stack_x)
        for left, right in zip(order, order[1:]):
            if right - left < outer_x:
                raise ValueError(
                    f"TES stacks at x={left:g} and x={right:g} m overlap: pitch must be >= Si_dx={outer_x:g} m"
                )
        abs_len = args.absorber_length if args.absorber_length else (max(stack_x) - min(stack_x) + abs_x)
        abs_cx = 0.5 * (max(stack_x) + min(stack_x))
    else:
        abs_len, abs_cx = abs_x, x0

    gmsh.initialize()
    gmsh.model.add("single_pixel_hybrid_prism" if not multi else f"multi_tes_{len(stack_x)}_hybrid_prism")
    gmsh.option.setNumber("General.Terminal", 1)
    # Horizontal footprint resolution.  Thickness is resolved by extrusion,
    # so the 1--20 um films do not force the absorber to use a 1--20 um 3-D
    # tetrahedral size.  This is the principal saving of the hybrid mesh.
    local_profiles = [
        q for q in (
            stack_local_field_profile(
                args.stack_local_size, args.stack_local_half_width, xc, y0, z_sio2_1, z_abs, args.global_mesh_size
            )
            for xc in stack_x
        ) if q is not None
    ]
    absorber_profiles = [
        q for q in (
            absorber_local_field_profile(
                args.absorber_local_size, args.absorber_local_radius, xc, y0, z_abs, abs_z, args.global_mesh_size
            )
            for xc in stack_x + [x0 + dx for dx in args.refine_x]
        ) if q is not None
    ]
    active_local_sizes = [q["VIn"] for q in local_profiles[:1] + absorber_profiles[:1]]
    global_min = min(active_local_sizes, default=args.global_mesh_size)
    gmsh.option.setNumber("Mesh.CharacteristicLengthMin", global_min)
    gmsh.option.setNumber("Mesh.CharacteristicLengthMax", args.global_mesh_size)
    gmsh.option.setNumber("Mesh.Algorithm", args.mesh_algorithm)
    gmsh.option.setNumber("Mesh.Algorithm3D", 4)
    gmsh.option.setNumber("Mesh.Optimize", 1)
    configure_mesh_size_options(args.disable_mesh_size_extend_from_boundary)

    volumes: dict[str, list[int]] = defaultdict(list)
    faces_by_name: dict[str, dict[str, list[int]]] = defaultdict(lambda: defaultdict(list))
    bath_faces: list[int] = []
    sty_tops: list[int] = []
    for xc, sfx in zip(stack_x, suffixes):
        ring, sty_top = _build_stack(
            args, p, xc, y0, sfx, volumes, faces_by_name,
            dict(z_sio2_2=z_sio2_2, z_sio2_1=z_sio2_1, z_tes=z_tes, z_sty=z_sty),
            (outer_x, outer_y, mem_x, mem_y, tes_x, tes_y, tes_z, sty_d, sty_z),
        )
        bath_faces += ring
        sty_tops += sty_top

    # Only the absorber is deliberately left to the 3-D tetrahedral mesher.
    abs_tag = gmsh.model.occ.addBox(abs_cx - abs_len / 2.0, y0 - abs_y / 2.0, z_abs, abs_len, abs_y, abs_z)
    if args.conformal_abs:
        # Imprint the Stycast disks into the absorber bottom.  Each imprinted
        # face gets its Stycast top mesh through an identity periodic map, and
        # ElmerGrid -merge then fuses the coincident nodes: no mortar remains.
        disks_abs = [gmsh.model.occ.addDisk(xc, y0, z_abs, sty_d / 2.0, sty_d / 2.0) for xc in stack_x]
        result, _ = gmsh.model.occ.fragment(
            [(3, abs_tag)], [(2, d) for d in disks_abs], removeObject=True, removeTool=True
        )
        abs_vols = [tag for dim, tag in result if dim == 3]
        if len(abs_vols) != 1:
            raise RuntimeError(f"absorber fragment produced {abs_vols}")
        abs_tag = abs_vols[0]
    gmsh.model.occ.synchronize()
    volumes["abs"].append(abs_tag)
    abs_faces = [face for dim, face in gmsh.model.getBoundary([(3, abs_tag)], False, False) if dim == 2]
    horizontal = sorted((gmsh.model.occ.getCenterOfMass(2, face)[2], face) for face in abs_faces)
    z_bottom = horizontal[0][0]
    bottom = [face for zc, face in horizontal if abs(zc - z_bottom) < 1.0e-9]
    top = [face for zc, face in horizontal if abs(zc - horizontal[-1][0]) < 1.0e-9]
    faces_by_name["abs"]["zmin"] += bottom
    faces_by_name["abs"]["zmax"] += top
    if args.conformal_abs:
        disk_area = math.pi * (sty_d / 2.0) ** 2
        disks = [f for f in bottom if abs(gmsh.model.occ.getMass(2, f) - disk_area) < 1.0e-4 * disk_area]
        if len(disks) != len(stack_x) or len(sty_tops) != len(stack_x):
            raise RuntimeError(f"cannot pair absorber disks {disks} with Stycast tops {sty_tops}")
        identity = [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]
        for sty_face in sty_tops:
            cx = gmsh.model.occ.getCenterOfMass(2, sty_face)[0]
            match = min(disks, key=lambda f: abs(gmsh.model.occ.getCenterOfMass(2, f)[0] - cx))
            gmsh.model.mesh.setPeriodic(2, [match], [sty_face], identity)
    _add_physical_volumes(volumes)
    _add_boundary_groups(faces_by_name, bath_faces)
    configure_local_fields(local_profiles, absorber_profiles)
    gmsh.model.mesh.generate(3)
    quality = measure_mesh_quality(suffixes)
    print(
        "mesh quality: "
        f"TES__zmin={quality['tes_face_elements']}, "
        f"Membrane_SiNx__zmax={quality['membrane_face_elements']}, "
        f"prisms={quality['prism_count']}, minSICN={quality['prism_min_sicn']:.6g}, "
        f"prisms<0.01={quality['prism_below_min_sicn']}"
    )
    for body, stats in quality["membrane_prism_stats"].items():
        print(
            f"mesh quality: {body} prisms={stats['prism_count']}, "
            f"minSICN={stats['prism_min_sicn']:.6g}, prisms<0.01={stats['prism_below_min_sicn']}"
        )
    if quality["reasons"]:
        for reason in quality["reasons"]:
            print(f"ERROR: mesh rejected: {reason}", file=sys.stderr)
        gmsh.finalize()
        raise RuntimeError("mesh quality gate rejected generated mesh; formal .msh was not written")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    gmsh.write(str(args.output))
    types, _, _ = gmsh.model.mesh.getElements(3)
    print("3-D Gmsh element types:", types, "(4=tetra, 6=prism)")
    print("wrote", args.output)
    gmsh.finalize()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
