"""Build the single-pixel hybrid mesh geometry.

The absorber remains an unstructured tetrahedral volume.  The supporting
stack is generated by extruding triangular 2-D footprints through each layer,
which produces 6-node prisms.  It intentionally writes a separate MSH file
(`gmsh/project_hybrid_prism.msh`) so it cannot overwrite the established
all-tetrahedral comparison mesh.
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import Counter, defaultdict
from pathlib import Path

import gmsh

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

from scripts.support.reconcile_project import reconcile_project


DEFAULT_OUT = ROOT / "gmsh" / "project_hybrid_prism.msh"
DEFAULT_PROJECT = ROOT / "elmer_project_comsol_timegrid.json"
GLOBAL_STACK_SIZE = 50.0e-6
MAX_INTERFACE_FACE_COUNT_RATIO = 4.0
MIN_PRISM_SICN = 0.01
MEMBRANE_PRISM_BODIES = ("Membrane_SiNx", "Membrane_Si1")
# OCC bounding boxes can differ from the analytic plane by roughly 1e-7 m.
TOL = 1.0e-8


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    """Parse the geometry recipe without initializing Gmsh.

    The optional stack probe is deliberately opt-in: absent arguments retain
    the established uniform 50 um hybrid geometry recipe.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("project", nargs="?", type=Path, default=DEFAULT_PROJECT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUT)
    parser.add_argument(
        "--global-mesh-size", type=float, default=GLOBAL_STACK_SIZE, metavar="METERS",
        help="uniform background size outside the local refinement fields (default: legacy 50 um)",
    )
    parser.add_argument(
        "--stack-local-size", type=float, default=None, metavar="METERS",
        help="central stack/contact Box-field size; omit for a uniform mesh at --global-mesh-size",
    )
    parser.add_argument(
        "--stack-local-half-width", type=float, default=0.4e-3, metavar="METERS",
        help="half-width of the central stack/contact refinement box (default: 0.4 mm)",
    )
    parser.add_argument(
        "--absorber-local-size", type=float, default=None, metavar="METERS",
        help="absorber-centre Ball-field size; omit for no absorber-local refinement",
    )
    parser.add_argument(
        "--absorber-local-radius", type=float, default=150e-6, metavar="METERS",
        help="radius of the absorber-centre refinement ball (default: 150 um)",
    )
    parser.add_argument(
        "--disable-mesh-size-extend-from-boundary", action="store_true",
        help="disable Gmsh Mesh.MeshSizeExtendFromBoundary for a local-field probe",
    )
    parser.add_argument(
        "--mesh-algorithm", type=int, choices=range(1, 10), default=6, metavar="ID",
        help="Gmsh 2-D mesh algorithm ID (default: 6, Frontal-Delaunay)",
    )
    parser.add_argument(
        "--stycast-diameter", type=float, default=498.0e-6, metavar="METERS",
        help="Stycast disk diameter; default retains the established 498 um geometry",
    )
    parser.add_argument(
        "--stycast-layers", type=int, default=1, metavar="COUNT",
        help="number of prism elements through the Stycast thickness (default: 1)",
    )
    for name, help_name in (
        ("sio2-2", "lower SiO2"),
        ("si-2", "lower Si"),
        ("sio2-1", "upper SiO2"),
        ("si-1", "upper Si"),
        ("sinx", "SiNx"),
        ("tes", "TES"),
    ):
        parser.add_argument(
            f"--{name}-layers", type=int, default=1, metavar="COUNT",
            help=f"number of prism elements through the {help_name} thickness (default: 1)",
        )
    args = parser.parse_args(argv)
    if args.global_mesh_size <= 0.0:
        parser.error("--global-mesh-size must be positive")
    if args.stack_local_size is not None and args.stack_local_size <= 0.0:
        parser.error("--stack-local-size must be positive")
    if args.stack_local_size is not None and args.stack_local_size > args.global_mesh_size:
        parser.error("--stack-local-size may not exceed --global-mesh-size")
    if args.stack_local_half_width <= 0.0:
        parser.error("--stack-local-half-width must be positive")
    if args.absorber_local_size is not None and args.absorber_local_size <= 0.0:
        parser.error("--absorber-local-size must be positive")
    if args.absorber_local_size is not None and args.absorber_local_size > args.global_mesh_size:
        parser.error("--absorber-local-size may not exceed --global-mesh-size")
    if args.absorber_local_radius <= 0.0:
        parser.error("--absorber-local-radius must be positive")
    if args.stycast_diameter <= 0.0:
        parser.error("--stycast-diameter must be positive")
    for name in ("stycast", "sio2_2", "si_2", "sio2_1", "si_1", "sinx", "tes"):
        if getattr(args, f"{name}_layers") < 1:
            parser.error(f"--{name.replace('_', '-')}-layers must be at least 1")
    return args


def stack_local_field_profile(
    local_size: float | None,
    half_width: float,
    x0: float,
    y0: float,
    z_sio2_1: float,
    z_abs: float,
    global_size: float = GLOBAL_STACK_SIZE,
) -> dict[str, float] | None:
    """Return a pure Gmsh Box-field profile for the optional stack probe."""
    if local_size is None or local_size >= global_size:
        return None
    return {
        "VIn": local_size,
        "VOut": global_size,
        "XMin": x0 - half_width,
        "XMax": x0 + half_width,
        "YMin": y0 - half_width,
        "YMax": y0 + half_width,
        # Extend one nominal global cell below SiO2_1 so the transition is
        # smooth through the membrane/stack column. The top is the absorber
        # contact plane; this necessarily refines tetrahedra adjacent to the
        # absorber-bottom interface but not the absorber bulk.
        "ZMin": z_sio2_1 - global_size,
        "ZMax": z_abs,
        "Thickness": global_size,
    }


def absorber_local_field_profile(
    local_size: float | None,
    radius: float,
    x0: float,
    y0: float,
    z_abs: float,
    abs_z: float,
    global_size: float = GLOBAL_STACK_SIZE,
) -> dict[str, float] | None:
    """Return a pure Gmsh Ball-field profile for absorber-centre refinement."""
    if local_size is None or local_size >= global_size:
        return None
    return {
        "VIn": local_size,
        "VOut": global_size,
        "XCenter": x0,
        "YCenter": y0,
        "ZCenter": z_abs + abs_z / 2.0,
        "Radius": radius,
        "Thickness": global_size,
    }


def configure_local_fields(
    stack_profile: dict[str, float] | None,
    absorber_profile: dict[str, float] | None,
) -> None:
    """Install optional Box/Ball fields, combining active fields with Min."""
    active_profiles = (("Box", stack_profile), ("Ball", absorber_profile))
    field_ids: list[int] = []
    for field_type, profile in active_profiles:
        if profile is None:
            continue
        field = gmsh.model.mesh.field.add(field_type)
        for name, value in profile.items():
            gmsh.model.mesh.field.setNumber(field, name, value)
        field_ids.append(field)
    if not field_ids:
        return
    if len(field_ids) == 1:
        gmsh.model.mesh.field.setAsBackgroundMesh(field_ids[0])
        return
    minimum = gmsh.model.mesh.field.add("Min")
    gmsh.model.mesh.field.setNumbers(minimum, "FieldsList", field_ids)
    gmsh.model.mesh.field.setAsBackgroundMesh(minimum)


def configure_stack_local_field(profile: dict[str, float] | None) -> None:
    """Compatibility adapter for callers that only install the stack Box field."""
    configure_local_fields(profile, None)


def configure_mesh_size_options(disable_extend_from_boundary: bool) -> None:
    """Apply the opt-in size-extension override without changing other sources."""
    if disable_extend_from_boundary:
        gmsh.option.setNumber("Mesh.MeshSizeExtendFromBoundary", 0)


def assess_mesh_quality(
    tes_face_elements: int,
    membrane_face_elements: int,
    membrane_prism_qualities: dict[str, list[float]],
) -> list[str]:
    """Return rejection reasons for the TES/membrane mesh quality contract.

    This deliberately contains no Gmsh calls so the acceptance thresholds are
    testable without generating a full 3-D mesh.
    """
    reasons: list[str] = []
    if tes_face_elements < 1 or membrane_face_elements < 1:
        reasons.append(
            "TES__zmin and Membrane_SiNx__zmax must both contain 2-D elements "
            f"(TES={tes_face_elements}, Membrane_SiNx={membrane_face_elements})"
        )
    else:
        ratio = max(tes_face_elements, membrane_face_elements) / min(tes_face_elements, membrane_face_elements)
        if ratio > MAX_INTERFACE_FACE_COUNT_RATIO:
            reasons.append(
                "TES__zmin/Membrane_SiNx__zmax 2-D element-count ratio "
                f"{ratio:.3g} exceeds {MAX_INTERFACE_FACE_COUNT_RATIO:g} "
                f"(TES={tes_face_elements}, Membrane_SiNx={membrane_face_elements})"
            )
    for body in MEMBRANE_PRISM_BODIES:
        qualities = membrane_prism_qualities.get(body, [])
        if not qualities:
            reasons.append(f"{body} contains no 6-node prism elements to evaluate")
            continue
        minimum = min(qualities)
        if minimum < MIN_PRISM_SICN:
            reasons.append(
                f"{body} prism minSICN {minimum:.6g} is below {MIN_PRISM_SICN:g} "
                f"({sum(value < MIN_PRISM_SICN for value in qualities)} prism elements below limit)"
            )
    return reasons


def _physical_surface_element_count(name: str) -> int:
    """Count all 2-D elements belonging to one named physical surface."""
    groups = [tag for dim, tag in gmsh.model.getPhysicalGroups(2) if gmsh.model.getPhysicalName(dim, tag) == name]
    if len(groups) != 1:
        raise RuntimeError(f"expected exactly one physical surface named {name!r}, got {len(groups)}")
    return sum(
        len(element_tags)
        for entity in gmsh.model.getEntitiesForPhysicalGroup(2, groups[0])
        for element_tags in gmsh.model.mesh.getElements(2, entity)[1]
    )


def _physical_volume_prism_qualities(name: str) -> list[float]:
    """Return minSICN values for 6-node prisms in one named physical volume."""
    groups = [tag for dim, tag in gmsh.model.getPhysicalGroups(3) if gmsh.model.getPhysicalName(dim, tag) == name]
    if len(groups) != 1:
        raise RuntimeError(f"expected exactly one physical volume named {name!r}, got {len(groups)}")
    prism_tags = [
        tag
        for entity in gmsh.model.getEntitiesForPhysicalGroup(3, groups[0])
        for element_type, tags in zip(*gmsh.model.mesh.getElements(3, entity)[:2])
        if element_type == 6
        for tag in tags
    ]
    return [float(value) for value in gmsh.model.mesh.getElementQualities(prism_tags, "minSICN")]


def measure_mesh_quality() -> dict:
    """Measure interface quality, retaining global and membrane-body diagnostics."""
    tes_face_elements = _physical_surface_element_count("TES__zmin")
    membrane_face_elements = _physical_surface_element_count("Membrane_SiNx__zmax")
    types, element_tags_by_type, _ = gmsh.model.mesh.getElements(3)
    prism_tags = [tag for element_type, tags in zip(types, element_tags_by_type) if element_type == 6 for tag in tags]
    prism_qualities = [float(value) for value in gmsh.model.mesh.getElementQualities(prism_tags, "minSICN")]
    membrane_qualities = {body: _physical_volume_prism_qualities(body) for body in MEMBRANE_PRISM_BODIES}
    membrane_stats = {
        body: {
            "prism_count": len(qualities),
            "prism_min_sicn": min(qualities) if qualities else float("nan"),
            "prism_below_min_sicn": sum(value < MIN_PRISM_SICN for value in qualities),
        }
        for body, qualities in membrane_qualities.items()
    }
    return {
        "tes_face_elements": tes_face_elements,
        "membrane_face_elements": membrane_face_elements,
        "prism_count": len(prism_qualities),
        "prism_min_sicn": min(prism_qualities) if prism_qualities else float("nan"),
        "prism_below_min_sicn": sum(value < MIN_PRISM_SICN for value in prism_qualities),
        "membrane_prism_stats": membrane_stats,
        "reasons": assess_mesh_quality(tes_face_elements, membrane_face_elements, membrane_qualities),
    }


def inspect_mesh_file(path: Path) -> dict[str, float | int | list[str]]:
    """Open an existing MSH and apply the same quality contract as generation.

    Gmsh is always finalized, including when opening or measuring fails, so a
    resume-time inspection cannot poison a later Gmsh invocation.
    """
    gmsh.initialize()
    try:
        gmsh.open(str(path))
        return measure_mesh_quality()
    finally:
        gmsh.finalize()


def _surface_at_z(tags: list[int], z: float) -> list[int]:
    result: list[int] = []
    for tag in tags:
        bb = gmsh.model.getBoundingBox(2, tag)
        if abs(bb[2] - z) < TOL and abs(bb[5] - z) < TOL:
            result.append(tag)
    return result


def _extrude(faces: list[int], dz: float, layers: int = 1) -> tuple[list[int], list[int]]:
    """Extrude triangular faces into prisms and return (volumes, top faces)."""
    result = gmsh.model.occ.extrude(
        [(2, face) for face in faces], 0.0, 0.0, dz,
        numElements=[layers], heights=[1.0], recombine=True,
    )
    volumes = [tag for dim, tag in result if dim == 3]
    gmsh.model.occ.synchronize()
    # OCC returns, for every input face, its translated top face first,
    # followed by the new volume and lateral faces.
    tops = [tag for dim, tag in result[: len(faces)] if dim == 2]
    return volumes, sorted(set(tops))


def _extrude_partitioned(faces: list[int], dz: float, layers: int = 1) -> list[tuple[int, int]]:
    """Extrude adjacent faces together and return (volume, top-face) pairs."""
    result = gmsh.model.occ.extrude(
        [(2, face) for face in faces], 0.0, 0.0, dz,
        numElements=[layers], heights=[1.0], recombine=True,
    )
    pairs = [
        (result[i + 1][1], tag)
        for i, (dim, tag) in enumerate(result[:-1])
        if dim == 2 and result[i + 1][0] == 3
    ]
    if len(pairs) != len(faces):
        raise RuntimeError(f"expected {len(faces)} extruded prism volumes, got {len(pairs)}")
    gmsh.model.occ.synchronize()
    return pairs


def _join_ring_and_centre(ring_faces: list[int], centre: int) -> tuple[list[int], list[int]]:
    """Make the membrane square share the ring's topological boundary."""
    result, _ = gmsh.model.occ.fragment(
        [(2, face) for face in ring_faces], [(2, centre)],
        removeObject=True, removeTool=True,
    )
    gmsh.model.occ.synchronize()
    faces = [tag for dim, tag in result if dim == 2]
    inner = [tag for tag in faces if gmsh.model.occ.getMass(2, tag) <= 1.01 * 0.7e-3 * 0.7e-3]
    outer = [tag for tag in faces if tag not in inner]
    if len(inner) != 1 or not outer:
        raise RuntimeError(f"failed to partition membrane footprint: inner={inner}, outer={outer}")
    return outer, inner


def _rectangle(xmin: float, xmax: float, ymin: float, ymax: float, z: float) -> int:
    return gmsh.model.occ.addRectangle(xmin, ymin, z, xmax - xmin, ymax - ymin)


def _ring(xmin: float, xmax: float, ymin: float, ymax: float, ixmin: float, ixmax: float, iymin: float, iymax: float, z: float) -> list[int]:
    outer = _rectangle(xmin, xmax, ymin, ymax, z)
    inner = _rectangle(ixmin, ixmax, iymin, iymax, z)
    faces, _ = gmsh.model.occ.cut([(2, outer)], [(2, inner)], removeObject=True, removeTool=True)
    gmsh.model.occ.synchronize()
    return [tag for dim, tag in faces if dim == 2]


def _add_physical_volumes(volumes: dict[str, list[int]]) -> None:
    for name, tags in volumes.items():
        gmsh.model.addPhysicalGroup(3, tags)
        gmsh.model.setPhysicalName(3, gmsh.model.getPhysicalGroups(3)[-1][1], name)


def _add_boundary_groups(faces_by_name: dict[str, dict[str, list[int]]], bath_faces: list[int]) -> None:
    # Keep the exact base/top faces returned by OCC extrusion.  Querying their
    # bounding boxes is unreliable here: OCC expands an analytic plane's box
    # by a tolerance larger than the 0.16 um TES thickness.
    for name, faces_by_side in faces_by_name.items():
        for suffix in ("zmin", "zmax"):
            # The bath is this exact physical face.  Gmsh/ElmerGrid retain
            # one physical label per boundary entity, so do not also name it
            # SiO2_2__zmin.
            if name == "SiO2_2" and suffix == "zmin":
                continue
            faces = sorted(set(faces_by_side.get(suffix, [])))
            if faces:
                group = gmsh.model.addPhysicalGroup(2, faces)
                gmsh.model.setPhysicalName(2, group, f"{name}__{suffix}")
    group = gmsh.model.addPhysicalGroup(2, bath_faces)
    gmsh.model.setPhysicalName(2, group, "bath")


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    raw = json.loads(args.project.read_text(encoding="utf-8"))
    model = reconcile_project(raw)
    p = model["parameters"]

    # Coordinates are derived from the same resolved single-pixel geometry as
    # mesh_refined_3x.  The lateral origin is x=0, y=1 mm.
    x0, y0 = 0.0, 1.0e-3
    outer_x, outer_y = p["Si_dx"], p["Si_dy"]
    mem_x, mem_y = p["membrane_dx"], p["membrane_dy"]
    abs_x, abs_y, abs_z = p["abs_dx"], p["abs_dy"], p["abs_dz"]
    tes_x, tes_y, tes_z = p["TES_Au_dx"], p["TES_Au_dy"], p["TES_dz"]
    sty_d, sty_z = args.stycast_diameter, p["Stycast_dz"]
    z0 = -0.5 * p["Si_2_dz"] - p["SiO2_2_dz"]
    z_sio2_2 = z0
    z_si2 = z_sio2_2 + p["SiO2_2_dz"]
    z_sio2_1 = z_si2 + p["Si_2_dz"]
    z_si1 = z_sio2_1 + p["SiO2_1_dz"]
    z_sinx = z_si1 + p["Si_1_dz"]
    z_tes = z_sinx + p["SiNx_dz"]
    z_sty = z_tes + tes_z
    z_abs = z_sty + sty_z

    ox0, ox1 = x0 - outer_x / 2.0, x0 + outer_x / 2.0
    oy0, oy1 = y0 - outer_y / 2.0, y0 + outer_y / 2.0
    mx0, mx1 = x0 - mem_x / 2.0, x0 + mem_x / 2.0
    my0, my1 = y0 - mem_y / 2.0, y0 + mem_y / 2.0

    gmsh.initialize()
    gmsh.model.add("single_pixel_hybrid_prism")
    gmsh.option.setNumber("General.Terminal", 1)
    # Horizontal footprint resolution.  Thickness is resolved by extrusion,
    # so the 1--20 um films do not force the absorber to use a 1--20 um 3-D
    # tetrahedral size.  This is the principal saving of the hybrid mesh.
    local_profile = stack_local_field_profile(
        args.stack_local_size, args.stack_local_half_width, x0, y0, z_sio2_1, z_abs, args.global_mesh_size
    )
    absorber_profile = absorber_local_field_profile(
        args.absorber_local_size, args.absorber_local_radius, x0, y0, z_abs, abs_z, args.global_mesh_size
    )
    active_local_sizes = [profile["VIn"] for profile in (local_profile, absorber_profile) if profile is not None]
    global_min = min(active_local_sizes, default=args.global_mesh_size)
    gmsh.option.setNumber("Mesh.CharacteristicLengthMin", global_min)
    gmsh.option.setNumber("Mesh.CharacteristicLengthMax", args.global_mesh_size)
    gmsh.option.setNumber("Mesh.Algorithm", args.mesh_algorithm)
    gmsh.option.setNumber("Mesh.Algorithm3D", 4)
    gmsh.option.setNumber("Mesh.Optimize", 1)
    configure_mesh_size_options(args.disable_mesh_size_extend_from_boundary)

    volumes: dict[str, list[int]] = defaultdict(list)
    faces_by_name: dict[str, dict[str, list[int]]] = defaultdict(lambda: defaultdict(list))
    ring = _ring(ox0, ox1, oy0, oy1, mx0, mx1, my0, my1, z_sio2_2)
    v, ring_top = _extrude(ring, p["SiO2_2_dz"], args.sio2_2_layers)
    volumes["SiO2_2"] += v
    faces_by_name["SiO2_2"]["zmin"] += ring
    faces_by_name["SiO2_2"]["zmax"] += ring_top
    bath_faces = list(ring)
    v, ring_top = _extrude(ring_top, p["Si_2_dz"], args.si_2_layers)
    volumes["Si_2"] += v
    faces_by_name["Si_2"]["zmin"] += faces_by_name["SiO2_2"]["zmax"]
    faces_by_name["Si_2"]["zmax"] += ring_top

    # At the Si_2 top the membrane cavity is closed by SiO2_1. Fragment the
    # existing Si_2 top face with the centre square, then extrude both faces
    # in one operation. This keeps all layer interfaces conforming.
    centre = _rectangle(mx0, mx1, my0, my1, z_sio2_1)
    ring_top, centre_faces = _join_ring_and_centre(ring_top, centre)
    faces_by_name["Si_2"]["zmax"] = list(ring_top)

    pairs = _extrude_partitioned(ring_top + centre_faces, p["SiO2_1_dz"], args.sio2_1_layers)
    split = len(ring_top)
    volumes["SiO2_1"] += [vol for vol, _ in pairs]
    faces_by_name["SiO2_1"]["zmin"] += ring_top + centre_faces
    ring_top = [top for _, top in pairs[:split]]
    centre_top = [top for _, top in pairs[split:]]
    faces_by_name["SiO2_1"]["zmax"] += ring_top + centre_top

    pairs = _extrude_partitioned(ring_top + centre_top, p["Si_1_dz"], args.si_1_layers)
    split = len(ring_top)
    volumes["Si_1"] += [vol for vol, _ in pairs[:split]]
    volumes["Membrane_Si1"] += [vol for vol, _ in pairs[split:]]
    faces_by_name["Si_1"]["zmin"] += ring_top
    faces_by_name["Membrane_Si1"]["zmin"] += centre_top
    ring_top = [top for _, top in pairs[:split]]
    centre_top = [top for _, top in pairs[split:]]
    faces_by_name["Si_1"]["zmax"] += ring_top
    faces_by_name["Membrane_Si1"]["zmax"] += centre_top

    pairs = _extrude_partitioned(ring_top + centre_top, p["SiNx_dz"], args.sinx_layers)
    split = len(ring_top)
    volumes["SiNx"] += [vol for vol, _ in pairs[:split]]
    volumes["Membrane_SiNx"] += [vol for vol, _ in pairs[split:]]
    faces_by_name["SiNx"]["zmin"] += ring_top
    faces_by_name["Membrane_SiNx"]["zmin"] += centre_top
    ring_top = [top for _, top in pairs[:split]]
    centre_top = [top for _, top in pairs[split:]]
    faces_by_name["SiNx"]["zmax"] += ring_top
    faces_by_name["Membrane_SiNx"]["zmax"] += centre_top

    tes = _rectangle(x0 - tes_x / 2.0, x0 + tes_x / 2.0, y0 - tes_y / 2.0, y0 + tes_y / 2.0, z_tes)
    v, _ = _extrude([tes], tes_z, args.tes_layers)
    volumes["TES"] += v
    faces_by_name["TES"]["zmin"] += [tes]
    faces_by_name["TES"]["zmax"] += _
    disk = gmsh.model.occ.addDisk(x0, y0, z_sty, sty_d / 2.0, sty_d / 2.0)
    v, _ = _extrude([disk], sty_z, layers=args.stycast_layers)
    volumes["Stycast"] += v
    faces_by_name["Stycast"]["zmin"] += [disk]
    faces_by_name["Stycast"]["zmax"] += _

    # Only the absorber is deliberately left to the 3-D tetrahedral mesher.
    abs_tag = gmsh.model.occ.addBox(x0 - abs_x / 2.0, y0 - abs_y / 2.0, z_abs, abs_x, abs_y, abs_z)
    gmsh.model.occ.synchronize()
    volumes["abs"].append(abs_tag)
    abs_faces = [face for dim, face in gmsh.model.getBoundary([(3, abs_tag)], False, False) if dim == 2]
    horizontal = sorted((gmsh.model.occ.getCenterOfMass(2, face)[2], face) for face in abs_faces)
    faces_by_name["abs"]["zmin"] += [horizontal[0][1]]
    faces_by_name["abs"]["zmax"] += [horizontal[-1][1]]
    _add_physical_volumes(volumes)
    _add_boundary_groups(faces_by_name, bath_faces)
    configure_local_fields(local_profile, absorber_profile)
    gmsh.model.mesh.generate(3)
    quality = measure_mesh_quality()
    print(
        "mesh quality: "
        f"TES__zmin={quality['tes_face_elements']}, "
        f"Membrane_SiNx__zmax={quality['membrane_face_elements']}, "
        f"prisms={quality['prism_count']}, minSICN={quality['prism_min_sicn']:.6g}, "
        f"prisms<0.01={quality['prism_below_min_sicn']}"
    )
    for body, stats in quality["membrane_prism_stats"].items():
        print(
            f"mesh quality: {body} prisms={stats['prism_count']}, "
            f"minSICN={stats['prism_min_sicn']:.6g}, prisms<0.01={stats['prism_below_min_sicn']}"
        )
    if quality["reasons"]:
        for reason in quality["reasons"]:
            print(f"ERROR: mesh rejected: {reason}", file=sys.stderr)
        gmsh.finalize()
        raise RuntimeError("mesh quality gate rejected generated mesh; formal .msh was not written")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    gmsh.write(str(args.output))
    types, _, _ = gmsh.model.mesh.getElements(3)
    print("3-D Gmsh element types:", types, "(4=tetra, 6=prism)")
    print("wrote", args.output)
    gmsh.finalize()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
