from __future__ import annotations

import csv
import json
import re
from pathlib import Path

from scripts.support.reconcile_project import numeric_drift_report, reconcile_project


ROOT = Path(__file__).resolve().parent
PARAMS_JSON = ROOT / "elmer_project.json"
GENERATED_DIR = ROOT / "generated"


def fmt(value: object) -> str:
    if isinstance(value, float):
        return f"{value:.16g}"
    return str(value)


def load_model() -> dict:
    """Load elmer_project.json and derive all numeric fields from their
    expressions (expressions-only schema). The file is never modified; a
    numeric value stored alongside an expression is legacy and gets flagged."""
    model = json.loads(PARAMS_JSON.read_text(encoding="utf-8"))
    reconciled = reconcile_project(model)
    drift = numeric_drift_report(model, reconciled)
    if drift:
        print(f"WARNING: {PARAMS_JSON.name} has numeric fields that contradict their expressions")
        print("         (expressions win; delete the stored numbers):")
        for line in drift:
            print(f"  {line}")
    return reconciled


def set_params_json(path: Path) -> None:
    global PARAMS_JSON
    PARAMS_JSON = path


def matc_temperature_expr(expr: str) -> str:
    expr = re.sub(r"\bT\b", "tx", expr)
    return expr.replace("**", "^")


def membrane_conductivity_at_t0(model: dict) -> float:
    params = model["parameters"]
    membrane_expr = str(model["materials"]["Membrane"]["k"]["expression"])
    python_expr = membrane_expr.replace("^", "**")
    values = {name: float(value) for name, value in params.items()}
    values["T"] = float(params["T_0"])
    return float(eval(python_expr, {"__builtins__": {}}, values))


def membrane_matc_expr(model: dict) -> str:
    membrane_expr = str(model["materials"]["Membrane"]["k"]["expression"])
    # Guard the non-integer power law against negative or zero iterates in
    # the nonlinear solve while preserving the original k(T) for T > 0.
    t_guard = "(0.5*((tx+1.0e-12)+abs(tx-1.0e-12)))"
    guarded_expr = re.sub(r"\bT\b", t_guard, membrane_expr)
    return guarded_expr.replace("**", "^")


def build_shared_variables(model: dict) -> str:
    params = model["parameters"]

    lines = [
        "! Auto-generated by sync_elmer_parameters.py",
        f"$ I_bias = {fmt(params['I_bias'])}",
        f"$ R_sh = {fmt(params['R_sh'])}",
        f"$ R0 = {fmt(params['R_0'])}",
        f"$ R_min = {fmt(params['R_min'])}",
        f"$ alpha = {fmt(params['alpha'])}",
        f"$ beta = {fmt(params['beta'])}",
        f"$ I0 = {fmt(params['I_0'])}",
        f"$ Tc = {fmt(params['T_c'])}",
        f"$ T0 = {fmt(params['T_0'])}",
        f"$ T_bath = {fmt(params['T_bath'])}",
        f"$ TES_volume = {fmt(params['TES_volume'])}",
        f"$ L_tes = {fmt(params['L_tes'])}",
        f"$ G0 = {fmt(params['G0'])}",
        f"$ membrane_dx = {fmt(params['membrane_dx'])}",
        f"$ TES_Au_dx = {fmt(params['TES_Au_dx'])}",
        f"$ SiNx_dz = {fmt(params['SiNx_dz'])}",
        f"$ Si_1_dz = {fmt(params['Si_1_dz'])}",
        f"$ SiO2_1_dz = {fmt(params['SiO2_1_dz'])}",
        f"$ T_initial_internal = T0",
        f"$ T_initial_transient = T0",
        f"$ T_initial_pulse = T0",
        "",
    ]
    return "\n".join(lines)


def build_materials_include(model: dict) -> str:
    materials = model["materials"]
    membrane = materials["Membrane"]
    membrane_k_matc = membrane_matc_expr(model)
    lines = [
        "! Auto-generated by sync_elmer_parameters.py",
        "Material 1",
        '  Name = "Pb"',
        f"  Density = {fmt(materials['Pb']['rho']['nominal'])}",
        f"  Heat Capacity = {fmt(materials['Pb']['cp']['nominal'])}",
        f"  Heat Conductivity = {fmt(materials['Pb']['k']['nominal'])}",
        "End",
        "",
        "Material 2",
        '  Name = "TES"',
        f"  Density = {fmt(materials['TES']['rho']['nominal'])}",
        f"  Heat Capacity = {fmt(materials['TES']['cp']['nominal'])}",
        f"  Heat Conductivity = {fmt(materials['TES']['k']['nominal'])}",
        "End",
        "",
        "Material 3",
        '  Name = "Stycast"',
        f"  Density = {fmt(materials['Stycast']['rho']['nominal'])}",
        f"  Heat Capacity = {fmt(materials['Stycast']['cp']['nominal'])}",
        f"  Heat Conductivity = {fmt(materials['Stycast']['k']['nominal'])}",
        "End",
        "",
        "Material 4",
        '  Name = "SiO2"',
        f"  Density = {fmt(materials['SiO2']['rho']['nominal'])}",
        f"  Heat Capacity = {fmt(materials['SiO2']['cp']['nominal'])}",
        f"  Heat Conductivity = {fmt(materials['SiO2']['k']['nominal'])}",
        "End",
        "",
        "Material 5",
        '  Name = "Si"',
        f"  Density = {fmt(materials['Si']['rho']['nominal'])}",
        f"  Heat Capacity = {fmt(materials['Si']['cp']['nominal'])}",
        f"  Heat Conductivity = {fmt(materials['Si']['k']['nominal'])}",
        "End",
        "",
        "Material 6",
        '  Name = "SiNx"',
        f"  Density = {fmt(materials['SiNx']['rho']['nominal'])}",
        f"  Heat Capacity = {fmt(materials['SiNx']['cp']['nominal'])}",
        f"  Heat Conductivity = {fmt(materials['SiNx']['k']['nominal'])}",
        "End",
        "",
        "Material 7",
        '  Name = "Membrane"',
        f"  Density = {fmt(membrane['rho']['nominal'])}",
        f"  Heat Capacity = {fmt(membrane['cp']['nominal'])}",
        "  Heat Conductivity = Variable Temperature",
        f'    Real MATC "{membrane_k_matc}"',
        "End",
        "",
    ]
    return "\n".join(lines)


def write_parameter_summary(model: dict) -> None:
    rows: list[dict[str, str]] = []
    params = model["parameters"]
    exprs = model["parameter_expressions"]
    unit_pattern = re.compile(r"\[\s*([a-zA-Z0-9/^*()\-]+)\s*\]")

    def unit_of(name: str) -> str:
        match = unit_pattern.search(str(exprs.get(name, "")))
        return match.group(1) if match else ""

    for name, value in params.items():
        rows.append(
            {
                "category": "parameter",
                "name": name,
                "value": fmt(value),
                "unit": unit_of(name),
                "expression": exprs.get(name, ""),
                "note": "",
            }
        )

    for mat_name, mat in model["materials"].items():
        for key in ("k", "rho", "cp"):
            nominal = mat[key].get("nominal")
            rows.append(
                {
                    "category": f"material:{mat_name}",
                    "name": key,
                    "value": fmt(nominal) if nominal is not None else "",
                    "unit": "",
                    "expression": mat[key]["expression"],
                    "note": "" if nominal is not None else "temperature-dependent",
                }
            )

    for name, value in model.get("elmer_overrides", {}).items():
        rows.append(
            {
                "category": "elmer_override",
                "name": name,
                "value": fmt(value),
                "unit": "",
                "expression": "",
                "note": "",
            }
        )

    for case_name, case_values in model.get("cases", {}).items():
        for name, value in case_values.items():
            rows.append(
                {
                    "category": f"case:{case_name}",
                    "name": name,
                    "value": json.dumps(value) if isinstance(value, (list, dict)) else fmt(value),
                    "unit": "",
                    "expression": "",
                    "note": "",
                }
            )

    out_path = GENERATED_DIR / "tes_parameter_summary.csv"
    with out_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(
            f, fieldnames=["category", "name", "value", "unit", "expression", "note"]
        )
        writer.writeheader()
        writer.writerows(rows)


def main() -> None:
    import sys

    args = sys.argv[1:]
    if args:
        set_params_json((ROOT / args[0]).resolve() if not Path(args[0]).is_absolute() else Path(args[0]))

    model = load_model()
    GENERATED_DIR.mkdir(exist_ok=True)

    (GENERATED_DIR / "tes_shared_variables.sif").write_text(
        build_shared_variables(model),
        encoding="utf-8",
    )
    (GENERATED_DIR / "tes_materials.sif").write_text(
        build_materials_include(model),
        encoding="utf-8",
    )

    from scripts.support.build_cases import build_all_cases

    written = build_all_cases(model, GENERATED_DIR / "cases", ROOT)
    print(f"generated/cases: {', '.join(written)}")

    write_parameter_summary(model)


if __name__ == "__main__":
    main()
