"""Readers shared by the plotting scripts for Analyze_Results outputs."""

import json
from pathlib import Path

import numpy as np
import pandas as pd


DEFAULT_ENERGY_TARGETS = ("Pulse_ms", "Pulse_ms_noise", "Pulse_noise")
ENERGY_COLUMNS = {"Sum", "Max", "Min", "ST"}


def result_path(folder: Path, target: str, filename: str) -> Path:
    """Find a current organized result, with a root-level legacy fallback."""
    folder = Path(folder)
    organized = folder / "results" / target.lower() / filename
    if organized.is_file():
        return organized
    return folder / filename


def find_energy_csv(folder: Path, target: str | None = None) -> Path:
    """Find an ``ene_resos_<target>.csv`` generated by Analyze_Results."""
    folder = Path(folder)
    if target is not None:
        path = result_path(folder, target, f"ene_resos_{target}.csv")
        if path.is_file():
            return path
        raise FileNotFoundError(f"Missing Analyze_Results CSV: {path}")

    for target_name in DEFAULT_ENERGY_TARGETS:
        path = result_path(folder, target_name, f"ene_resos_{target_name}.csv")
        if path.is_file():
            return path

    found = sorted(folder.glob("ene_resos_*.csv")) + sorted(
        (folder / "results").glob("*/ene_resos_*.csv")
    )
    if len(found) == 1:
        return found[0]
    names = ", ".join(path.name for path in found) or "none"
    raise FileNotFoundError(
        f"No unambiguous Analyze_Results energy-resolution CSV in {folder}; found: {names}"
    )


def load_energy_resolution(folder: Path, target: str | None = None) -> pd.DataFrame:
    """Read an energy-resolution CSV and index it by physical x [mm].

    Older ``Analyze_Results`` versions wrote the x coordinate as an unnamed
    CSV index.  Treat that sole, conventional legacy index column as ``x_mm``
    so existing result directories remain plottable.
    """
    path = find_energy_csv(folder, target)
    data = pd.read_csv(path)
    legacy_index_columns = [
        column for column in data.columns
        if str(column).strip().lower().startswith("unnamed:")
    ]
    if "x_mm" not in data.columns and len(legacy_index_columns) == 1:
        data = data.rename(columns={legacy_index_columns[0]: "x_mm"})
    if "x_mm" not in data.columns:
        raise ValueError(
            f"{path} is missing the Analyze_Results x-coordinate column 'x_mm'"
        )
    missing = ENERGY_COLUMNS - set(data.columns)
    if missing:
        raise ValueError(
            f"{path} is missing current Analyze_Results columns: {', '.join(sorted(missing))}"
        )
    return data.set_index("x_mm")


def absorber_x_positions(folder: Path) -> np.ndarray:
    """Convert Analyze_Results absorber-block positions to the x_mm convention."""
    input_path = Path(folder) / "input.json"
    with open(input_path, encoding="utf-8") as file:
        parameters = json.load(file)
    blocks = np.asarray(parameters["position"], dtype=float)
    return (
        blocks - (float(parameters["n_abs"]) + 1.0) / 2.0
    ) * float(parameters["length"]) / float(parameters["n_abs"])


def load_position_resolution(folder: Path, target: str) -> tuple[np.ndarray, np.ndarray]:
    """Read ``fwhms_<target>.txt`` with x coordinates matching energy CSVs."""
    path = result_path(folder, target, f"fwhms_{target}.txt")
    if not path.is_file():
        raise FileNotFoundError(f"Missing Analyze_Results position-resolution file: {path}")
    fwhm = np.atleast_1d(np.loadtxt(path, dtype=float))
    x_mm = absorber_x_positions(folder)
    if len(fwhm) != len(x_mm):
        raise ValueError(
            f"{path} has {len(fwhm)} values, but input.json defines {len(x_mm)} positions"
        )
    return x_mm, fwhm
